[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[preferences.MPIPreferences]
_format = "1.1"
abi = "MPICH"
binary = "system"
cclibs = ["pmi", "pmi2", "pthread", "pals", "rt", "pthread", "pmi", "pmi2"]
libmpi = "libmpi_nvidia.so"
mpiexec = "mpiexec"
preloads = ["libmpi_gtl_cuda.so"]
preloads_env_switch = "MPICH_GPU_SUPPORT_ENABLED"

