#!/bin/bash

# Run this job by typing
# $ qsub -I interactive_job.bash

#PBS -N interactive
#PBS -A ucsg0002 
#PBS -j oe
#PBS -q main
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=64:mpiprocs=4:ngpus=4:mem=30GB
#PBS -l gpu_type=a100

export JULIA_NUM_PRECOMPILE_TASKS=64
export JULIA_NUM_THREADS=64

module purge
module load ncarenv/23.09 nvhpc/24.1 cuda/12.2.1 cray-mpich/8.1.27
export MPICH_GPU_SUPPORT_ENABLED=1