#!/bin/bash
nodes=1
cpus=4
ntasks=1
threads_per_task=$(( cpus / ntasks )) 
jobn=cpu-cc-testing-4-1-mpiexecjl-openmpi1
output_dir=outputs/new-cpu-testing/
project_dir=/glade/work/apauls/.julia/environments/cc-testing-oc-mpiexecjl/
rm -rf $output_dir$jobn
mkdir $output_dir$jobn

cp langmuir_turb-cpu.jl $output_dir$jobn/
cp stokes.jl $output_dir$jobn/

cd $output_dir$jobn/

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166 
#PBS -N $jobn
#PBS -q develop
#PBS -j oe
####PBS -l job_priority=economy
#PBS -l walltime=4:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$ntasks

export JULIA_NUM_PRECOMPILE_TASKS=$cpus
export JULIA_NUM_THREADS=$cpus

# Load critical modules
module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

# GPU-specific variables are not needed for CPU runs
unset MPICH_GPU_SUPPORT_ENABLED
unset MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED
unset JULIA_MPI_HAS_CUDA
unset JULIA_CUDA_MEMORY_POOL

export PALS_TRANSFER=false
cd $WORK/3d_langmuir_gpu/$output_dir$jobn/

####echo "Instantiating project..."
####julia --project=$project_dir -e 'using Pkg; Pkg.instantiate()'
####echo "Resolving project..."
####julia --project=$project_dir -e 'using Pkg; Pkg.resolve()'
####echo "Developing Oceananigans..."
####julia --project=$project_dir -e 'using Pkg; Pkg.develop(path="/glade/work/apauls/personal-oceananigans/Oceananigans.jl-main")' 
####echo "Adding necessary packages..."
####julia --project=$project_dir -e 'using Pkg; Pkg.add("MPI"); Pkg.add("MPIPreferences"); Pkg.add("Printf"); Pkg.add("Statistics"); Pkg.add("Random")'
####echo "Building MPI-related packages..."
julia --project=$project_dir -e 'using Pkg; Pkg.build("MPI"); Pkg.build("MPIPreferences")'
julia --project=$project_dir -e 'using MPIPreferences; MPIPreferences.use_system_binary()'
####julia --project=$project_dir -e 'using MPI; MPI.install_mpiexecjl(force=true)'
julia --project=$project_dir -e 'using MPIPreferences; MPIPreferences.use_jll_binary("OpenMPI_jll")'
echo "Instantiating project again..."
julia --project=$project_dir -e 'using Pkg; Pkg.instantiate()'


cd $WORK/3d_langmuir_gpu/$output_dir$jobn/
echo "Running simulation with mpiexecjl..."
mpiexecjl --project=$project_dir -n $ntasks langmuir_turb-cpu.jl
EXEC

qsub EXEC_STEP