#!/bin/bash
nodes=1
gpus=1
cpus=64
ntasks=$((nodes*gpus))
threads_per_task=$(( cpus / ntasks ))
jobn=cpu-baseline-cc-32
output_dir=outputs/agu-poster/
project_dir=/glade/work/apauls/.julia/environments/v1.10/
file_name=langmuir_turb-bgc-cpu.jl
rm -rf $output_dir$jobn
mkdir $output_dir$jobn

cp $file_name $output_dir$jobn/

cd $output_dir$jobn/
module --force purge
cat > launch.sh << EoF_s

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166
#PBS -N $jobn
#PBS -q develop
#PBS -j oe
###PBS -l job_priority=economy
#PBS -l walltime=6:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$gpus:ngpus=$gpus:gpu_type=cc80

export JULIA_NUM_PRECOMPILE_TASKS=$cpus
export JULIA_NUM_THREADS=$cpus

module load ncarenv nvhpc cuda cray-mpich

module list

# GPU-specific variables are not needed for CPU runs
export JULIA_CUDA_USE_BINARYBUILDER=false
export JULIA_CUDA_VISIBLE_DEVICES=""
export JULIA_CUDA_IGNORE_WARNINGS=true

unset MPICH_GPU_SUPPORT_ENABLED
unset MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED
unset JULIA_MPI_HAS_CUDA
unset JULIA_CUDA_MEMORY_POOL

##julia --project=$project_dir -e 'import Pkg'
##julia --project=$project_dir -e 'using Pkg; Pkg.instantiate()'
##julia --project=$project_dir -e 'using Pkg; Pkg.resolve()'
julia --project=$project_dir -e 'using Pkg; Pkg.develop(path="/glade/work/apauls/personal-oceananigans/OceanBioME.jl-main/")'
julia --project=$project_dir -e 'using Pkg; Pkg.add("OceanBioME")'

mpiexec -n $ntasks julia --project=$project_dir $WORK/3d_langmuir_gpu/$output_dir$jobn/langmuir_turb-cpu.jl
EXEC


qsub < EXEC_STEP