#!/bin/bash
nodes=1
cpus=128
procs=32
ntasks=$((nodes*procs))
threads=$((cpus/procs))
base_dir=/glade/derecho/scratch/apauls/outputs
archive_folder=small-horizontal-domain
jobn=modified-default
file=T-periodicboundary.jl

rm -rf $base_dir/$archive_folder/$jobn/
mkdir $base_dir/$archive_folder/$jobn/

cp $file $base_dir/$archive_folder/$jobn/

cd $base_dir/$archive_folder/$jobn/

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166
#PBS -N $jobn
#PBS -q main 
#PBS -j oe
#PBS -l job_priority=economy
#PBS -l walltime=3:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$procs

export JULIA_NUM_PRECOMPILE_TASKS=$threads
export JULIA_NUM_THREADS=$threads

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

julia --project -e 'import Pkg'
julia --project -e 'using Pkg; Pkg.instantiate()'
julia --project -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name="Oceananigans", version="0.106.6"))'
mpiexec -n $ntasks -ppn $procs julia --project $file

EXEC

qsub < EXEC_STEP