#!/bin/bash
nodes=1
cpus=128
procs=1
ntasks=$((nodes*procs))
jobn=test-dist-cpus

rm -rf outputs/$jobn
mkdir outputs/$jobn

cp langmuir_turb.jl outputs/$jobn/

cd outputs/$jobn/

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166 
#PBS -N $jobn
#PBS -q main 
#PBS -j oe
#PBS -l job_priority=economy
#PBS -l walltime=0:30:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$procs

export JULIA_NUM_PRECOMPILE_TASKS=$cpus
export JULIA_NUM_THREADS=$cpus

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

##julia --project -e 'import Pkg'
##julia --project -e 'using Pkg; Pkg.instantiate()'
julia --project langmuir_turb.jl

EXEC

qsub < EXEC_STEP