#!/bin/bash
nodes=1
cpus=64
gpus=1
ntasks=$((nodes*gpus))
jobn=cc-withinrk3

rm -rf outputs/$jobn
mkdir outputs/$jobn

cp langmuir_turb.jl outputs/$jobn/
cp stokes.jl outputs/$jobn/

cd outputs/$jobn/
touch Project.toml

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166 
#PBS -N $jobn
#PBS -q main
#PBS -j oe
#PBS -l job_priority=economy
#PBS -l walltime=0:20:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$gpus:ngpus=$gpus
#PBS -l gpu_type=a100

export JULIA_NUM_PRECOMPILE_TASKS=$cpus
export JULIA_NUM_THREADS=$cpus

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cuda/12.2.1 cray-mpich/8.1.29

module list

export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED=1
export JULIA_MPI_HAS_CUDA=true
export PALS_TRANSFER=false
export JULIA_CUDA_MEMORY_POOL=none

julia --project -e 'import Pkg'
julia --project -e 'using Pkg; Pkg.instantiate()'
julia --project -e 'using Pkg; Pkg.resolve()'
julia --project -e 'Pkg.develop(path="/glade/work/apauls/.julia/dev/Oceananigans.jl-main")' 
# 2. Update packages to the environment that we need to use. not always necessary
julia --project -e 'using Pkg; Pkg.add("MPI"); Pkg.add("MPIPreferences"); Pkg.add("CUDA"); Pkg.add("Printf"); Pkg.add("Statistics"); Pkg.add("Random"); Pkg.add("DifferentialEquations")'
# Tell MPI that we would like to use the system binary we loaded with module load cray-mpich
julia --project -e 'using MPIPreferences; MPIPreferences.use_system_binary(vendor="cray", force=true)'
# Only need to run if you want to reset or update things (did you update the amount of  nodes and processors?)
julia --project -e 'using MPI; using CUDA; CUDA.precompile_runtime()'
# Finally, let's run this thing

mpiexec -n $ntasks -ppn $gpus set_gpu_rank julia --project langmuir_turb.jl
EXEC

qsub < EXEC_STEP
