#!/bin/bash
nodes=1
cpus=16
ntasks=1
threads_per_task=$(( nodes * cpus / ntasks ))
jobn=cpu-baseline-cc-32-1
output_dir=outputs/agu-poster/
project_dir=/glade/work/apauls/.julia/environments/v1.10/
file_name=langmuir_turb-bgc-cpu.jl
rm -rf $output_dir$jobn
mkdir $output_dir$jobn

cp $file_name $output_dir$jobn/

cd $output_dir$jobn/

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166
#PBS -N $jobn
#PBS -q main
#PBS -j oe
#PBS -l job_priority=premium
#PBS -l walltime=12:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$ntasks

export FFTW_NUM_THREADS=1
export OMP_NUM_THREADS=1

export JULIA_NUM_PRECOMPILE_TASKS=$threads_per_task
export JULIA_NUM_THREADS=$threads_per_task

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

##julia --project=$project_dir -e 'import Pkg'
##julia --project=$project_dir -e 'using Pkg; Pkg.instantiate()'
##julia --project=$project_dir -e 'using Pkg; Pkg.resolve()'
julia --project=$project_dir -e 'using Pkg; Pkg.develop(path="/glade/work/apauls/personal-oceananigans/OceanBioME.jl-main/")'
julia --project=$project_dir -e 'using Pkg; Pkg.add("OceanBioME")'

julia --project=$project_dir $file_name
EXEC


qsub < EXEC_STEP