#!/bin/bash
LD_LIBRARY_PATH = /opt/cray/pe/cti/2.18.3/lib:/opt/cray/pe/pmi/6.1.14/lib:/opt/cray/pe/mpich/8.1.29/ofi/intel/2022.1/lib:/opt/cray/libfabric/1.15.2.0/lib64:/opt/cray/libfabric/1.15.2.0/lib:/glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/2024.2/opt/compiler/lib:/glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/2024.2/lib:/glade/u/apps/casper/24.12/spack/opt/spack/gcc/12.4.0/5b5c/lib64:/glade/u/apps/derecho/24.12/spack/opt/spack/hdf5/1.12.3/oneapi/2024.2.1/peu3/lib

nodes=1
cpus=128
ntasks=$((nodes*cpus))
jobn=sgs_force_smag_comparison_cpus
rm -rf outputs/$jobn
mkdir outputs/$jobn

cp langmuir_turb_sgs.jl outputs/$jobn/
cp langmuir_turb_forcing.jl outputs/$jobn/
cp stokes.jl outputs/$jobn/
cp smagorinsky_forcing.jl outputs/$jobn/

cd outputs/$jobn/
touch Project.toml

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166 
#PBS -N $jobn
#PBS -q main
#PBS -j oe
#PBS -l job_priority=economy
#PBS -l walltime=1:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$cpus
#PBS -l gpu_type=a100

export LD_LIBRARY_PATH=/glade/u/home/apauls/software/julia-1.10.8/lib:$LD_LIBRARY_PATH
export JULIA_NUM_PRECOMPILE_TASKS=$cpus
export JULIA_NUM_THREADS=$cpus

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

julia --project -e 'import Pkg'
julia --project -e 'using Pkg; Pkg.instantiate()'
julia --project -e 'using Pkg; Pkg.gc()'
# 2. Update packages to the environment that we need to use. not always necessary
julia --project -e 'using Pkg; Pkg.add("MPI"); Pkg.add("MPIPreferences"); Pkg.add("KernelAbstractions"); Pkg.add("Oceananigans"); Pkg.add("Printf"); Pkg.add("Statistics"); Pkg.add("Random")'
# Tell MPI that we would like to use the system binary we loaded with module load cray-mpich
julia --project -e 'using MPIPreferences; MPIPreferences.use_system_binary(vendor="cray", force=true)'


mpiexec -n $ntasks julia --project langmuir_turb_forcing_cpu.jl
mpiexec -n $ntasks julia --project langmuir_turb_sgs_cpu.jl
EXEC

qsub < EXEC_STEP