#!/bin/bash
nodes=1
cpus=64
gpus=1
ntasks=$((nodes*gpus))
jobn=sgs_force_smag

rm -rf outputs/$jobn
mkdir outputs/$jobn

cp langmuir_turb_sgs.jl outputs/$jobn/
cp langmuir_turb_forcing.jl outputs/$jobn/
cp stokes.jl outputs/$jobn/
cp smagorinsky_forcing.jl outputs/$jobn/

cd outputs/$jobn/
touch Project.toml

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166 
#PBS -N $jobn
#PBS -q main
#PBS -j oe
#PBS -l job_priority=economy
#PBS -l walltime=1:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$gpus:ngpus=$gpus
#PBS -l gpu_type=a100

touch Project.toml

export JULIA_NUM_PRECOMPILE_TASKS=$cpus
export JULIA_NUM_THREADS=$cpus

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cuda/12.2.1 cray-mpich/8.1.29

module list

export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED=1
export JULIA_MPI_HAS_CUDA=true
export PALS_TRANSFER=false
export JULIA_CUDA_MEMORY_POOL=none

julia --project -e 'import Pkg'
julia --project -e 'using Pkg; Pkg.instantiate()'
julia --project -e 'using Pkg; Pkg.add("MPI"); Pkg.add("MPIPreferences"); Pkg.add("CUDA"); Pkg.add("Oceananigans"); Pkg.add("Printf"); Pkg.add("Statistics"); Pkg.add("Random");  Pkg.add("KernelAbstractions")'
# Tell MPI that we would like to use the system binary we loaded with module load cray-mpich
julia --project -e 'using MPIPreferences; MPIPreferences.use_system_binary(vendor="cray", force=true)'
julia --project -e 'using MPI; using CUDA; CUDA.precompile_runtime()'

mpiexec -n $ntasks -ppn $gpus set_gpu_rank julia --project langmuir_turb_forcing.jl
EXEC

qsub < EXEC_STEP