#!/bin/bash
nodes=4
cpus=128
procs=16
ntasks=$((nodes*procs))
nthreads=$((cpus/procs))
base_dir=/glade/derecho/scratch/apauls/outputs/version109/gaussian
jobn=dxi025
file=T-periodicboundary.jl

mkdir -p $base_dir/$jobn

cp $file $base_dir/$jobn

cd $base_dir/$jobn

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166
#PBS -N $jobn
#PBS -q main 
#PBS -j oe
#PBS -l job_priority=economy
#PBS -l walltime=5:00:00
#PBS -l select=$nodes:ncpus=$cpus:mpiprocs=$procs

export JULIA_NUM_PRECOMPILE_TASKS=$nthreads
export JULIA_NUM_THREADS=$nthreads

module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

###julia --project -e 'import Pkg'
###julia --project -e 'using Pkg; Pkg.instantiate()'
###julia --project -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name="Oceananigans", version="0.109.1"))'
mpiexec -n $ntasks -ppn $procs julia --project $file

EXEC

qsub < EXEC_STEP