#!/bin/bash
nodes=1
cpus=128
ntasks=4
threads_per_task=$(( cpus / ntasks ))
jobn=model-cpu-test
file_name=test_distributed_models.jl

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166 
#PBS -N $jobn
#PBS -q develop
#PBS -j oe
####PBS -l job_priority=premium
#PBS -l walltime=04:00:00
#PBS -l select=$nodes:ncpus=$threads_per_task:mpiprocs=$ntasks

export JULIA_NUM_PRECOMPILE_TASKS=$threads_per_task
export JULIA_NUM_THREADS=$threads_per_task

# Load critical modules
module --force purge
module load ncarenv/23.09 nvhpc/24.7 cray-mpich/8.1.29

module list

# GPU-specific variables are not needed for CPU runs
export JULIA_CUDA_USE_BINARYBUILDER=false
export JULIA_CUDA_VISIBLE_DEVICES=""
export JULIA_CUDA_IGNORE_WARNINGS=true

unset MPICH_GPU_SUPPORT_ENABLED
unset MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED
unset JULIA_MPI_HAS_CUDA
unset JULIA_CUDA_MEMORY_POOL

export PALS_TRANSFER=false

module list

mpiexec -n $ntasks julia --project $file_name
EXEC

qsub < EXEC_STEP
